#!/usr/bin/env node

var path = require('path');
var fs = require("fs");
var lib = path.join(path.dirname(fs.realpathSync(__filename)), 
					"index.js");
console.log(lib);
require(lib).run(process.argv.slice(2)); 
